name: 프로젝트 명
description: "프로젝트 설명"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 상태 관리
  provider: ^6.1.2
  # 라우팅
  go_router: ^14.7.2
  # Firebase
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  firebase_storage: ^12.4.1
  cloud_firestore: ^5.6.2
  google_sign_in: ^6.2.1
  # Utils
  shared_preferences: ^2.4.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - .env